[project]
name = "taler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "elevenlabs>=2.26.1",
    "mlx-whisper>=0.4.3",
    "mutagen>=1.47.0",
    "numpy>=2.3.5",
    "sounddevice>=0.5.3",
]
